### ISSUE TITLE
SSL Problems

### ISSUE THREAD

**Issue by thyrymn** [FreedomCoder/Cartero#2]
If the site has certificate problems, it won't clone:

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:858:in `start'
/usr/local/rvm/gems/ruby-2.2.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
/usr/local/rvm/gems/ruby-2.2.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
/usr/local/rvm/gems/ruby-2.2.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
/usr/local/rvm/gems/ruby-2.2.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:259:in `fetch'
/usr/local/rvm/gems/ruby-2.2.1/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
/root/Cartero/lib/cartero/commands/cloner.rb:127:in `clone'
/root/Cartero/lib/cartero/commands/cloner.rb:108:in `run'
/root/Cartero/lib/cartero/command.rb:82:in `block in method_added'
/root/Cartero/lib/cartero/cli.rb:190:in `block in run'
/root/Cartero/lib/cartero/cli.rb:184:in `each'
/root/Cartero/lib/cartero/cli.rb:184:in `run'
./cartero:52:in `<main>'

**Comment by FreedomCoder** [comment]
I was aware of cartero checking certs. I guess you are right, I should have a flag to disable checks.  --no-ssl-checks ;) ?

**Comment by FreedomCoder** [comment]
Problem Fixed, found another issue with 403. trying to handle things a little better now. I'll push an update soon so you can test it.

**Comment by FreedomCoder** [comment]
@thyrymn can you check the new update and make sure it fixed your problem. I checked w/ 2 sites and it  now works and fails nicely as well :+1:

**Comment by thyrymn** [comment]
Yep.  Fixed.
