### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thyrymn** [FreedomCoder/Cartero#8]
I get a pretty good crash no matter what site I mirror when I attempt a login page, BSON pops up on the website too when I push the logon button.

2015-06-10 14:50:41 - BSON::InvalidKeyName - key org.apache.struts.taglib.html.TOKEN must not contain '.':
        /usr/local/rvm/gems/ruby-2.2.1/gems/bson-1.12.3/lib/bson/bson_c.rb:20:in `serialize'
        /usr/local/rvm/gems/ruby-2.2.1/gems/bson-1.12.3/lib/bson/bson_c.rb:20:in `serialize'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo-1.12.3/lib/mongo/collection_writer.rb:219:in `block in send_write_operation'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo-1.12.3/lib/mongo/collection_writer.rb:218:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo-1.12.3/lib/mongo/collection_writer.rb:218:in `send_write_operation'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo-1.12.3/lib/mongo/collection.rb:1106:in `send_write'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo-1.12.3/lib/mongo/collection.rb:419:in `insert'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:136:in `save_to_collection'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations.rb:88:in `save_to_collection'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/safe.rb:27:in `save_to_collection'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:126:in `create'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:21:in `block in create'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_callbacks.rb:77:in `run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:21:in `create'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:121:in `create_or_update'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:17:in `block in create_or_update'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_callbacks.rb:77:in `run_callbacks'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:17:in `create_or_update'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:103:in `save'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:17:in `block in save'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:27:in `clear_changes'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:17:in `save'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/validations.rb:22:in `save'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/identity_map.rb:87:in `save'
        /usr/local/rvm/gems/ruby-2.2.1/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:108:in `save!'
        /root/Cartero/lib/cartero/sinatra_helpers.rb:36:in `process_cred'
        /tmp/website/website.rb:42:in `block in <class:Website>'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by FreedomCoder** [comment]
As usual thanks for the issue report. You always keep me busy. I'll need a little help from you to reproduce it. What exactly your run and what you were trying to clone !?

**Comment by FreedomCoder** [comment]
It looks like is failing for some table key name error containing a . and based on the error I can trace it back to https://github.com/FreedomCoder/Cartero/blob/master/lib/cartero/sinatra_helpers.rb#L36  Now, I need to know exactly what is being saved to see if I have an error somewhere.

**Comment by thyrymn** [comment]
What do you need?  It is a username and password and a crapton of cookies, near the old 2k cookie limit.  I'll work on getting you more tonight or tomorrow,

**Comment by FreedomCoder** [comment]
If you can share the site even privately it will help a lot. Otherwise I'll do my best to replicate without it and you comments.

**Comment by thyrymn** [comment]
This one is my own fault.  Debian default mongo was old.  Be sure to have mongo 3+ installed.

**Comment by FreedomCoder** [comment]
No problemo. Thanks, yet another reason why to use mongodb 3+. I guess I should make a check and fail to start if the DB is not a specific version.

**Comment by thyrymn** [comment]
Or in the Debian instruction part, tell them that apt-get doesn't work out if the box, you gotta go get it out of the mongo repos.

**Comment by FreedomCoder** [comment]
Will do thanks for the comment and the issue reporting. Keep them coming ;)
